const VIXEN_DATABASE = [
    // NIVÅ 1: FLIRT (30 st)
    { id: "vix_n1_01", level: 1, text: "Bit dig i underläppen medan du tittar lite för länge på någon." },
    { id: "vix_n1_02", level: 1, text: "Råka nämna en sexfantasi för någon, som om det bara slank ur dig." },
    { id: "vix_n1_03", level: 1, text: "Råka flasha lite för mycket hud, utan att det blir vulgärt." },
    { id: "vix_n1_04", level: 1, text: "Bjud upp någon till dans och håll det extra kroppsnära." },
    { id: "vix_n1_05", level: 1, text: "Dra långsamt tungan över läppen medan du håller kvar blicken på någon." },
    { id: "vix_n1_06", level: 1, text: "Slicka sexigt på flaskan du dricker ur medan du håller ögonkontakt." },
    { id: "vix_n1_07", level: 1, text: "Viska något riktigt snuskigt i någons öra." },
    { id: "vix_n1_08", level: 1, text: "Ge någon en överdrivet sexig komplimang om deras kropp." },
    { id: "vix_n1_09", level: 1, text: "Håll ögonkontakt i 10 sekunder – avsluta med en blinkning." },
    { id: "vix_n1_10", level: 1, text: "Skicka ett snuskigt sms 'av misstag' till någon, förklara sen att det var fel person." },
    { id: "vix_n1_11", level: 1, text: "Ta en utmanande selfie, råka låta någon få syn på den." },
    { id: "vix_n1_12", level: 1, text: "Råka slicka av lite från ditt finger – håll ögonkontakt." },
    { id: "vix_n1_13", level: 1, text: "Håll någons hand lite för länge och släpp långsamt." },
    { id: "vix_n1_14", level: 1, text: "Råka stöna till på ett sätt som låter alldeles för snuskigt." },
    { id: "vix_n1_15", level: 1, text: "Berätta om en gång du var riktigt kåt, som om det bara råkade slinka ur dig." },
    { id: "vix_n1_16", level: 1, text: "Luta dig fram mot någon så att din kropp nuddar deras." },
    { id: "vix_n1_17", level: 1, text: "Släng ur dig en snuskig fråga och låtsas att du inte tänkte dig för." },
    { id: "vix_n1_18", level: 1, text: "Håll kvar blicken och slicka dig långsamt om munnen." },
    { id: "vix_n1_19", level: 1, text: "Sätt dig så nära någon att ni nuddar varandra hela tiden." },
    { id: "vix_n1_20", level: 1, text: "Se någon i ögonen och säg 'Jag vill ha dig' – skratta bort det sen." },
    { id: "vix_n1_21", level: 1, text: "Håll kvar handen på någons arm längre än normalt." },
    { id: "vix_n1_22", level: 1, text: "Dra ner tröjan lite för långt när du 'rättar till' den." },
    { id: "vix_n1_23", level: 1, text: "Böj dig fram så någon får en kittlande glimt ner i urringningen." },
    { id: "vix_n1_24", level: 1, text: "Ta ett steg för nära någon så att era kroppar nuddar när ni pratar." },
    { id: "vix_n1_25", level: 1, text: "Säg ett oskyldigt ord på ett sätt som får det att låta förbjudet." },
    { id: "vix_n1_26", level: 1, text: "Låt blicken fastna på någons läppar, slicka dig om munnen när du blir påkommen." },
    { id: "vix_n1_27", level: 1, text: "Vrid kroppen så att en sexig detalj syns mer än tänkt." },
    { id: "vix_n1_28", level: 1, text: "Stöna tyst för dig själv som om du var i egna tankar." },
    { id: "vix_n1_29", level: 1, text: "Låt blicken vandra öppet över någons kropp och le utmanande." },
    { id: "vix_n1_30", level: 1, text: "Stanna upp mitt i en mening och mumla något oanständigt." },

    // NIVÅ 2: TEASE (30 st)
    { id: "vix_n2_01", level: 2, text: "Sätt dig i knät på någon och säg: 'Ojdå, jag trodde du var en jag kände'." },
    { id: "vix_n2_02", level: 2, text: "Ställ dig bakom någon och viska något riktigt snuskigt i deras öra." },
    { id: "vix_n2_03", level: 2, text: "Vänd dig om nära någon och låt kroppen snudda vid deras bröst eller höft." },
    { id: "vix_n2_04", level: 2, text: "Sätt dig på huk framför någon och håll kvar ögonkontakten med ett leende." },
    { id: "vix_n2_05", level: 2, text: "Tryck dig lite extra nära när du dansar med någon." },
    { id: "vix_n2_06", level: 2, text: "Ge någon en kyss på kinden, alldeles för nära mungipan." },
    { id: "vix_n2_07", level: 2, text: "Låt någon hjälpa dig att dra ner en dragkedja eller knäppa upp en knapp." },
    { id: "vix_n2_08", level: 2, text: "Ge någon en snabb kyss på halsen." },
    { id: "vix_n2_09", level: 2, text: "Råka tappa något och plocka upp det på ett utmanande sätt." },
    { id: "vix_n2_10", level: 2, text: "Be någon känna hur mjuk din hud är på armen." },
    { id: "vix_n2_11", level: 2, text: "Byt plats så att du måste pressa din kropp tätt förbi någon." },
    { id: "vix_n2_12", level: 2, text: "Stryk med handen över nacken och ge en förförisk blick." },
    { id: "vix_n2_13", level: 2, text: "Sätt dig på bordskanten bredvid någon så benen nuddar varandra." },
    { id: "vix_n2_14", level: 2, text: "Sträck på dig så tröjan åker upp och blottar hud vid troskanten." },
    { id: "vix_n2_15", level: 2, text: "Sitt i kort kjol och låt fingrarna glida upp längs insidan av låret." },
    { id: "vix_n2_16", level: 2, text: "Stoppa långsamt in pekfingertoppen i munnen medan du håller ögonkontakt." },
    { id: "vix_n2_17", level: 2, text: "Sitt iförd kjol och 'råka' flasha trosorna när du sätter dig ner." },
    { id: "vix_n2_18", level: 2, text: "Låt din hand vila på någons rygg och glida ner mot höften innan du släpper." },
    { id: "vix_n2_19", level: 2, text: "Låt fingrarna glida längs någons hals ner mot nyckelbenet." },
    { id: "vix_n2_20", level: 2, text: "Dra upp eller ner ett plagg lite för långt och håll det så i några sekunder." },
    { id: "vix_n2_21", level: 2, text: "Applicera läppbalsam extremt långsamt med ögonkontakt." },
    { id: "vix_n2_22", level: 2, text: "Krama någon bakifrån och spela generad: 'Ojdå, trodde det var nån annan'." },
    { id: "vix_n2_23", level: 2, text: "Sitt i kjol och låt den glida upp så trosorna syns tydligt." },
    { id: "vix_n2_24", level: 2, text: "Låt handen glida längs din egen kropp och stanna vid höften när du pratar." },
    { id: "vix_n2_25", level: 2, text: "Lek med ditt halsband och dra det långsamt mellan brösten." },
    { id: "vix_n2_26", level: 2, text: "Stå i baren så brösten snuddar någons rygg, säg förlåt med ett leende." },
    { id: "vix_n2_27", level: 2, text: "Rätta till kjolen eller byxorna långsamt medan du ser någon i ögonen." },
    { id: "vix_n2_28", level: 2, text: "Låt ditt knä stryka mot någons knä upprepade gånger." },
    { id: "vix_n2_29", level: 2, text: "Sträck dig efter något så din kropp pressas mot någon i en sekund." },
    { id: "vix_n2_30", level: 2, text: "Sitt i kjol och korsa benen långsamt med oavbruten ögonkontakt." },

    // NIVÅ 3: TEMPTATION (30 st)
    { id: "vix_n3_01", level: 3, text: "Låt handen vila högt upp på någons lår medan ni sitter bredvid varandra." },
    { id: "vix_n3_02", level: 3, text: "Dansa tryckare och låt läpparna snudda personens öra." },
    { id: "vix_n3_03", level: 3, text: "Kyss någon på halsen mitt på dansgolvet." },
    { id: "vix_n3_04", level: 3, text: "Sätt dig i någons knä i baren som om det vore självklart." },
    { id: "vix_n3_05", level: 3, text: "Låt handen glida ner över någons rumpa och kläm till lite." },
    { id: "vix_n3_06", level: 3, text: "Tryck dig mot någon när du går förbi och stanna kvar en sekund för länge." },
    { id: "vix_n3_07", level: 3, text: "För diskret ner en persons hand på din rumpa när ni dansar." },
    { id: "vix_n3_08", level: 3, text: "Flirta öppet med en främling tills du får en tydlig respons." },
    { id: "vix_n3_09", level: 3, text: "Gnid kroppen mot någon i baren eller på dansgolvet." },
    { id: "vix_n3_10", level: 3, text: "Dansa tryckare och bjud in till en djup kyss." },
    { id: "vix_n3_11", level: 3, text: "Be om en kyss och ta den mitt framför ögonen på andra." },
    { id: "vix_n3_12", level: 3, text: "Luta dig bakåt i baren och gnid din rumpa mot någons skrev." },
    { id: "vix_n3_13", level: 3, text: "Ta tag i någons nacke och dra ansiktet hårt mot ditt." },
    { id: "vix_n3_14", level: 3, text: "Smek någons lår öppet i baren." },
    { id: "vix_n3_15", level: 3, text: "Tryck din rumpa mot någons skrev på dansgolvet och håll kvar." },
    { id: "vix_n3_16", level: 3, text: "Följ någons käklinje med fingertoppen och viska något hett." },
    { id: "vix_n3_17", level: 3, text: "Smek din egen kropp från halsen ner mot brösten medan du dansar." },
    { id: "vix_n3_18", level: 3, text: "Dra händerna över någons mage ner mot deras höfter bakifrån." },
    { id: "vix_n3_19", level: 3, text: "Pressa ditt underliv lätt mot någons rumpa på dansgolvet." },
    { id: "vix_n3_20", level: 3, text: "Ta någons hand och placera den högt upp på ditt eget lår." },
    { id: "vix_n3_21", level: 3, text: "Låt handen glida bakåt över någons rumpa mitt i en rörelse." },
    { id: "vix_n3_22", level: 3, text: "Be en främling i baren om en kyss." },
    { id: "vix_n3_23", level: 3, text: "Pressa hela din kropp mot någon på dansgolvet och rör dig i takt." },
    { id: "vix_n3_24", level: 3, text: "Böj dig sakta ner framför någon så deras blick hamnar precis rätt." },
    { id: "vix_n3_25", level: 3, text: "Låt din hand glida upp längs insidan av någons lår under bordet." },
    { id: "vix_n3_26", level: 3, text: "Kyss någon djupt mitt bland folk." },
    { id: "vix_n3_27", level: 3, text: "Sätt dig gränsle över någons lår vid ett bord." },
    { id: "vix_n3_28", level: 3, text: "Låt din hand snudda någons hud under tröjan vid ländryggen." },
    { id: "vix_n3_29", level: 3, text: "Låtsas säga något men ge en puss på kinden i stället." },
    { id: "vix_n3_30", level: 3, text: "För någons hand till ditt bröst och håll kvar blicken." },

    // NIVÅ 4: RISK (30 st)
    { id: "vix_n4_01", level: 4, text: "Låt två personer smeka dig samtidigt, uppe och nere." },
    { id: "vix_n4_02", level: 4, text: "Tryck upp någon mot väggen och kyss dem hårt." },
    { id: "vix_n4_03", level: 4, text: "Låt någon gnida kuken mot din rumpa genom kläderna mot en vägg." },
    { id: "vix_n4_04", level: 4, text: "Låt flera händer smeka dig samtidigt på dansgolvet." },
    { id: "vix_n4_05", level: 4, text: "Ta dig utanför lokalen och ge någon en avsugning i mörkret." },
    { id: "vix_n4_06", level: 4, text: "Låt någon stoppa in ett finger i dig snabbt och dolt i lokalen." },
    { id: "vix_n4_07", level: 4, text: "Låt någon dra ner dina trosor ett ögonblick i ett halvmörkt hörn." },
    { id: "vix_n4_08", level: 4, text: "Ha en het grind mot någons skrev medan din partner ser på." },
    { id: "vix_n4_09", level: 4, text: "Dra ner någons gylf i ett hörn, ge några drag och stoppa in den igen." },
    { id: "vix_n4_10", level: 4, text: "Gå till toaletten för en snabb avsugning, filma om möjligt." },
    { id: "vix_n4_11", level: 4, text: "Sitt i knät på någon och rör dig mot deras skrev genom kläderna." },
    { id: "vix_n4_12", level: 4, text: "Låt någon ta dig bakifrån i bilen medan din partner kör." },
    { id: "vix_n4_13", level: 4, text: "Sug av någon i baksätet medan partnern ser i backspegeln." },
    { id: "vix_n4_14", level: 4, text: "Rida någon snabbt i baksätet medan partnern kör." },
    { id: "vix_n4_15", level: 4, text: "Stanna bilen på ett mörkt ställe och låt honom slicka dig." },
    { id: "vix_n4_16", level: 4, text: "Ge en avsugning i baksätet under färd genom stan." },
    { id: "vix_n4_17", level: 4, text: "Dra ner någons byxor och ge snabba sug medan partnern håller vakt." },
    { id: "vix_n4_18", level: 4, text: "Låt två personer hålla fast dig medan en tredje smeker dig." },
    { id: "vix_n4_19", level: 4, text: "Låt honom slicka dig på toaletten, se till att det filmas." },
    { id: "vix_n4_20", level: 4, text: "Låt någon dra upp din topp och blotta brösten en kort stund." },
    { id: "vix_n4_21", level: 4, text: "Låt någon trycka kuken mot dig öppet på dansgolvet." },
    { id: "vix_n4_22", level: 4, text: "Följ med en främling mellan bilarna för en avsugning." },
    { id: "vix_n4_23", level: 4, text: "Ta med någon ut i gränden och ge en avsugning i mörkret." },
    { id: "vix_n4_24", level: 4, text: "Gå på toaletten och låt honom sätta på dig hårt, filma allt." },
    { id: "vix_n4_25", level: 4, text: "Låt två personer använda dig samtidigt i eller vid en bil." },
    { id: "vix_n4_26", level: 4, text: "Låt någon ta dig snabbt mot väggen bakom lokalen." },
    { id: "vix_n4_27", level: 4, text: "Blotta bröstvårtan mitt bland folk, snabbt men tydligt." },
    { id: "vix_n4_28", level: 4, text: "Låt två killar turas om att kyssa dig medan partnern ser på." },
    { id: "vix_n4_29", level: 4, text: "Låt honom smeka dig innanför trosorna vid en rökplats." },
    { id: "vix_n4_30", level: 4, text: "Ta honom i munnen i ett mörkt hörn medan partnern vaktar." },

    // NIVÅ 5: NO LIMITS (32 st)
    { id: "vix_n5_01", level: 5, text: "Sug av två killar samtidigt på klubben medan partnern ser på." },
    { id: "vix_n5_02", level: 5, text: "Bli använd av flera män i följd under en planerad kväll." },
    { id: "vix_n5_03", level: 5, text: "Gå ner på knä och sug av en främling inför andra gäster." },
    { id: "vix_n5_04", level: 5, text: "Möt en kille din partner valt och låt honom sätta på dig hårt." },
    { id: "vix_n5_05", level: 5, text: "Ta emot en kuk i munnen och en i fittan samtidigt." },
    { id: "vix_n5_06", level: 5, text: "Ta med två killar hem och knulla dem framför din partner." },
    { id: "vix_n5_07", level: 5, text: "Låt partnern välja en kille online som sedan får knulla dig." },
    { id: "vix_n5_08", level: 5, text: "Genomför ett gangbang där partnern styr tempot." },
    { id: "vix_n5_09", level: 5, text: "Låt en ta dig bakifrån medan du suger en annan som partnern valt." },
    { id: "vix_n5_10", level: 5, text: "Träffa någon från en kontaktsida och knulla inför partnern." },
    { id: "vix_n5_11", level: 5, text: "Låt flera killar turas om att knulla dig i en gunga." },
    { id: "vix_n5_12", level: 5, text: "Bli uppspänd och låt flera män använda alla dina hål samtidigt." },
    { id: "vix_n5_13", level: 5, text: "Låt partnern binda dig naken och släppa in män en efter en." },
    { id: "vix_n5_14", level: 5, text: "Gå upp i showroom och låt främlingar turas om att ta dig." },
    { id: "vix_n5_15", level: 5, text: "Genomför en Air Tight (tre män samtidigt i alla hål)." },
    { id: "vix_n5_16", level: 5, text: "Låt män knulla dig i följd utan att partnern själv deltar." },
    { id: "vix_n5_17", level: 5, text: "Genomför en DVP (dubbel vaginal penetration) med åskådare." },
    { id: "vix_n5_18", level: 5, text: "Ge dig hän direkt till en främling som partnern tar med hem." },
    { id: "vix_n5_19", level: 5, text: "Låt flera killar knulla dig i ett gloryhole medan partnern ser." },
    { id: "vix_n5_20", level: 5, text: "Ordna ett gangbang med en hel grupp män." },
    { id: "vix_n5_21", level: 5, text: "Bli bunden och knullad av flera män tills du är helt slut." },
    { id: "vix_n5_22", level: 5, text: "Låt partnern bestämma vem du ska knulla – du får inte neka någon." },
    { id: "vix_n5_23", level: 5, text: "Låt dig användas i ett lekrum tills du knappt kan stå." },
    { id: "vix_n5_24", level: 5, text: "Låt män använda dig tills partnern säger att det räcker." },
    { id: "vix_n5_25", level: 5, text: "Ge dig hän till alla män på en privat fest." },
    { id: "vix_n5_26", level: 5, text: "Ta emot män i omgångar hela natten på hotell." },
    { id: "vix_n5_27", level: 5, text: "Låt två män spruta på dina bröst samtidigt inför partnern." },
    { id: "vix_n5_28", level: 5, text: "Genomför en DP (dubbel penetration) med partnern bredvid." },
    { id: "vix_n5_29", level: 5, text: "Låt främlingar ta dig i mörkerrummet medan partnern ser." },
    { id: "vix_n5_30", level: 5, text: "Bli gangbangad av minst fem män under en hotellkväll." },
    { id: "vix_n5_31", level: 5, text: "Stanna i din Vixen-roll under en hel maratonnatt." },
    { id: "vix_n5_32", level: 5, text: "Överlämna dig helt till de tyngsta uppdragen utan spärrar." }
];